export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const LOAD_PRODUCT = 'LOAD_PRODUCT'
export const MOBILE_CATEGORY_OPEN = 'MOBILE_CATEGORY_OPEN'
export const MOBILE_CATEGORY_CLOSE = 'MOBILE_CATEGORY_CLOSE'
export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'
export const GET_CATEGORY_PRODUCTS = 'GET_CATEGORY_PRODUCTS'
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const UPDATE_SORT = 'UPDATE_SORT'
export const SORT_PRODUCT = 'SORT_PRODUCT'
export const UPDATE_PRICE = 'UPDATE_PRICE'
export const CHANGE_PRICE = 'CHANGE_PRICE'






